# Generated by Django 3.2.25 on 2024-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0085_address_validation_skipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE account_user
            ALTER COLUMN full_name
            SET DEFAULT '';
            """,
            migrations.RunSQL.noop,
        ),
    ]
